name: store_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.0
  string_validator: ^0.3.0
  firebase_core: "^1.6.0"
  firebase_auth: "^3.1.1"
  cloud_firestore:
  firebase_storage:
  provider: ^6.0.2
  image_picker: ^0.8.4+5
  enum_to_string: ^1.0.14
  logger: ^0.9.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.8
  flutter_rating_bar: ^4.0.0
  swipedetector: ^1.2.0
  url_launcher:
  flutter_launcher_icons:
  flutter_svg:
  flutter_tags:
  future_progress_dialog:
  permission_handler: ^8.2.5
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "images/moma-logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/splash.png
    - images/profil.jpg
    - images/outboard_image1.png
    - images/outboard_image2.png
    - images/outboard_image3.png
    - images/main_order.png
    - images/success_pay_image.png
    - images/bag.png
    - images/bag_black.png
    - images/big_bag.png
    - images/Bg.png
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BesleyBlack
      fonts:
        - asset: fonts/Besley-Regular.ttf
        - asset: fonts/Besley-Italic.ttf
          style: italic
        - asset: fonts/Besley-Black.ttf
          weight: 900
        - asset: fonts/Besley-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Besley-Bold.ttf
          weight: 700
        - asset: fonts/Besley-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Besley-ExtraBold.ttf
          weight: 800
        - asset: fonts/Besley-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: fonts/Besley-Medium.ttf
          weight: 500
        - asset: fonts/Besley-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Besley-SemiBold.ttf
          weight: 600
        - asset: fonts/Besley-SemiBoldItalic.ttf
          weight: 600
          style: italic


    - family: LobsterRegular
      fonts:
        - asset: fonts/Lobster-Regular.ttf
          weight: 400
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: false
